[package]
name = "beat-detector"
description = "Audio beat detection library."
version = "0.0.0"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lowpass-filter = "0.2.3"
spectrum-analyzer = "0.5.0"
cpal = "0.13.3"

[dev-dependencies]
minimp3 = "0.5.1"


# otherwise FFT and other code is too slow
[profile.dev]
opt-level = 1

